spring.application.name=api-monitoramento-transformadores

spring.datasource.url=jdbc:h2:mem:gestaodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.port=8181

springdoc.swagger-ui.path=/swagger-ui.html
# Ordena os Controllers (Tags) em ordem alfabética
springdoc.swagger-ui.tagsSorter=alpha
# Ordena os endpoints dentro do controller com base no método HTTP (DELETE, GET, POST, PUT)
springdoc.swagger-ui.operationsSorter=method
